name: Build
on: [push, pull_request]
env:
  NUM_THREADS: 16

jobs:
  ubuntu:
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name
    name: ${{ matrix.config.os }} ${{ matrix.config.cxx }} ${{ matrix.config.note }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        build_type: ["Debug", "RelWithDebInfo", "Release"]
        config:
          - {
            os: ubuntu-latest,
            cc: "gcc-11", cxx: "g++-11"
          }
          - {
            os: ubuntu-latest,
            cc: "clang-17", cxx: "clang++-17"
          }

    steps:
      - uses: actions/checkout@v2
      - name: Set up toolchain repositories
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main"
      - name: Install Compiler
        run: |
          sudo apt-get update
          sudo apt-get -qq install ${{matrix.config.cc}} ${{matrix.config.cxx}}
      - name: Install Dependencies
        run: |
          sudo apt-get -qq install libboost-program-options-dev libhwloc-dev libjemalloc-dev build-essential libstdc++-12-dev
      - name: Configure
        run: |
          mkdir build && cd build
          CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_ASAN_TESTS=On ..
      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ulimit -s 65532
          ctest --no-tests=error --output-on-failure

  macos:
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name
    name: macos-latest AppleClang (${{matrix.build_type}})
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: ["Debug", "RelWithDebInfo", "Release"]
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install Dependencies
        run: |
          brew install hwloc boost jemalloc llvm
      - name: Echo Clang Version
        run: clang --version
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_ASAN_TESTS=On ..
      - name: Build
        run: |
          cd build
          cmake --build .
      - name: Test
        run: |
          cd build
          sudo ulimit -s 65532
          ctest -C Debug --no-tests=error --output-on-failure

  msvc:
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name
    name: windows-latest MSVC 19 (${{matrix.build_type}})
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: ["Debug", "RelWithDebInfo", "Release"]
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Configure
        run: |
          md build
          cd build
          cmake -A x64 DBUILD_ASAN_TESTS=On -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_FLAGS=" /bigobj /F 65532000 " ..
      - name: Build
        run: |
          cd build
          cmake --build .
      - name: Test
        run: |
          cd build
          ctest -C Debug --no-tests=error --output-on-failure
